### ISSUE TITLE
跑在docker容器里会出错，dll加载失败

### ISSUE THREAD

**Issue by microestc** [jacovis/Javi.MediaInfo#1]
Exception on LoadLibrary(/app/wwwroot/dll/x64/MediaInfo.dll):  ---> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Javi.MediaInfo.PInvoke.LoadLibrary(String dllToLoad)
   at Javi.MediaInfo.MediaInfoWrapper..ctor(String mediaInfoDLLFullName)
   --- End of inner exception stack trace ---

**Comment by jacovis** [comment]
In what kind of environment are you using the code? 
Is PInvoke for loading the mediainfo.dll supported? 
Please elaborate (in english) exactly what the steps are to reproduce this error.

**Comment by microestc** [comment]
public class MediaInfoSvc : IMediaInfoSvc
    {
        private readonly string _dllUrl;

        public MediaInfoSvc(IHostingEnvironment env, IOptions<Settings> options)
        {
            var dir = options?.Value?.MediaInfoDllDir;
            if (string.IsNullOrWhiteSpace(dir)) throw new ArgumentNullException("not found settings data of mediainfo.dll");
            _dllUrl = Path.Combine(env.WebRootPath, dir, "MediaInfo.dll");
            if (!File.Exists(_dllUrl)) throw new Exception("not found the file of mediainfo.dll");
        }

        public int GetMediaDuration(string fileUrl)
        {
            var duration = TimeSpan.Zero;
            using (MediaInfoWrapper mediaInfo = new MediaInfoWrapper(_dllUrl))
            {
                mediaInfo.Open(fileUrl);
                try
                {
                    if (double.TryParse(mediaInfo.Get(StreamKind.General, 0, "Duration"), NumberStyles.Any, CultureInfo.InvariantCulture, out double result))
                    {
                        duration = TimeSpan.FromMilliseconds(result);
                    }
                }
                catch { }
            }
            return (int)duration.TotalSeconds;
        }

    }

in windows enable to run ,but in docker is failed ,Exception on LoadLibrary(/app/wwwroot/dll/x64/MediaInfo.dll)
ok, i used ffmpeg to do the same of things

**Comment by jacovis** [comment]
The mediainfo.dll is dynamically loaded using windows interop. A call to PInvoke is used to load the DLL. Since you are able to run your code succesfully in windows, I assume it is a problem with your docker config. This is out of the scope of my code. I suggest you investigate the config of your docker environment and especially regarding LoadLibrary, pinvoke and anything else the exception tells you.

**Comment by microestc** [comment]
ok,think you.Once I find the cause of the problem, I will submit the solution.

**Comment by jacovis** [comment]
Looking forward to it!

**Comment by microestc** [comment]
https://github.com/microestc/ffmpeg for docker
