### ISSUE TITLE
General --> Title

### ISSUE THREAD

**Issue by r-e-n-e-g-i** [jacovis/Javi.MediaInfo#2]
Hello,

for video files, often the title can be found in General --> Title and not as separate Text stream. It would be great if you could add that property.

**Comment by jacovis** [comment]
Could you give an example of a video file where Title can be found in the General information?

**Comment by r-e-n-e-g-i** [comment]
The value should be available directly from the Title property:

value = GetValue(Stream_General, "Title");

**Comment by jacovis** [comment]
Again, can you give an example of a video file where the General Information contains Title? I need this to be able to test the change.

**Comment by r-e-n-e-g-i** [comment]
Unfortunately, I do not have a test video, but you could download the following:
[https://www.nichehospitality.com/wp-content/uploads/2015/11/SampleVideo_1080x720_1mb.mp4](url)
and add a test title via Windows Explorer property window

I just saw that there is no album, title or performer for audio files. Do you plan to add those properties in the near future?

**Comment by jacovis** [comment]
I have commited a new version: Added property Title to GeneralInfo class; accessible via MediaInfo.General.Title. The sample.mp4 properties have been edited to include a title to be shown when running the demo console application.

You are right that for audio files the album,title or performer are missing. I will add these as well in the coming days.

**Comment by jacovis** [comment]
Commited new version 1.0.8 and updated nuget package to also contain new properties for audio files as well, see commit https://github.com/jacovis/Javi.MediaInfo/commit/9504b4d9013b658c4ad41197a13a27d816186a51

**Comment by r-e-n-e-g-i** [comment]
Thank you.
