### ISSUE TITLE
Invoke' has unbalanced the stack

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [jacovis/Javi.MediaInfo#3]
Hi, I just tried your wrapper with the latest version of the MediaInfo.dll and when using New MediaInfo(exePath) I get the error ..

A call to PInvoke function 'Javi.MediaInfo!Javi.MediaInfo.MediaInfoWrapper+MediaInfo_Option::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

Any thoughts?

**Comment by jacovis** [comment]
The latest version today is 19.09, see https://mediaarea.net/en/MediaInfo/Download/Windows
Download the dll [64 bit](https://mediaarea.net/download/binary/libmediainfo0/19.09/MediaInfo_DLL_19.09_Windows_x64_WithoutInstaller.zip) or [32 bit](https://mediaarea.net/download/binary/libmediainfo0/19.09/MediaInfo_DLL_19.09_Windows_i386_WithoutInstaller.zip) from that link and please retry. 
With 19.09 I am unable to replicate the behaviour you report.
Furthermore, what environment are you running? Windows version, VS/C# version etc etc. 
Have you tried downloading the source from here and compiling and running the demo?

**Comment by jacovis** [comment]
Closed issue due to no response. Assume problem solved by using the correct mediainfo.dll
