### ISSUE TITLE
Failed to load the dll dynamically.

### ISSUE THREAD

**Issue by kcvinker** [jacovis/Javi.MediaInfo#4]
Hi,
I put the dll in my app's exe folder, but it shows that it is failing to load the dll dynamically,
First i used just the name of dll like - new MediaInfo("MediaInfo.dll") It failed and then i put the full path, but it also failed.
I have tested both 32 bit dll and 64 bit dll. My pc is 64 bit. But when testing with 32 bit dll, i think it detected the dll, but an error message showed like something is not matching bla bla.

**Comment by jacovis** [comment]
Have you tried downloading the source from here and compiling and running the demo? Can you provide the exact error message? Is the error message an exception in your own code or an operating system message?

**Comment by kcvinker** [comment]
Thanks for the reply.
1. I have used Nuget package manager console to install this package. I have downloaded MediaInfo dll from their page.
2. I will present a detailed picture of error message soon.
3. Actually, i don't remember that. Let me try the same code once again.

**Comment by kcvinker** [comment]
I am closing this issue because, now i am using mediaInfo's cli version. And i can easily get the results from Process.OutputDataReceived event.
